### PR TITLE
Create MIT.md

### PR DESCRIPTION
**Pull request by mm-pazouki**
It is merged before by mistake and about this PR https://github.com/mm-pazouki/Portfolio/pull/8
Add mobile menu functionality
MIT.md file created
In this pull request, I implement the following features:

- When the user clicks (or taps) the hamburger button, the mobile menu appears.
- When the user clicks (or taps) the close (X) button, the mobile menu disappears.
- When the user clicks (or taps) any of the mobile menu options, the mobile menu disappears.
- When the user clicks (or taps) any of the mobile menu options, a correct part of the page is displayed.

### CODE REVIEW

**Comment by mm-pazouki** [comment]
Actual PR is here check the link https://github.com/mm-pazouki/Portfolio/pull/8

**Comment by topeogunleye** [comment]
Hi @mm-pazouki, 

   - You have submitted a project, that doesn't have a pull request description, kindly add one. See a demo on how to add a PR description below:

pull_request_desc
Cheers and Happy coding!👏👏👏

Kindly click on the three dots on the top right of your PR Description to edit and add a description.

image

**Comment by topeogunleye** [comment]
> Actual PR is here check the link #8

@mm-pazouki, Thank you. Please add a more descriptive pull request summary underneath your current statement of It is merged before by mistake and about this PR https://github.com/mm-pazouki/Portfolio/pull/8. e.g:

```
##Portfolio: Milestone 5 Mobile Menu

In this pull request, I implement the following features:

- When the user clicks (or taps) the hamburger button, the mobile menu appears.
- When the user clicks (or taps) the close (X) button, the mobile menu disappears.
- When the user clicks (or taps) any of the mobile menu options, the mobile menu disappears.
- When the user clicks (or taps) any of the mobile menu options, a correct part of the page is displayed.
```

**Review by topeogunleye — APPROVED** [review]
### Hi @mm-pazouki, 

# Status: Approved ✔️
I noticed that you created a new pull request for the changes requested in this pr: https://github.com/mm-pazouki/Portfolio/pull/8. In the future, please do not create new pull requests for rereviews. Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
congratulations
>
## To highlight :champagne: 
- Created MIT license file as suggested :heavy_check_mark: 
 
## [Optional] suggestions:
- [ ] Hi, nice work on the project. I have reviewed your code and everything looks good. I have only one optional suggestion for future projects that involve the use of JavaScript, HTML and CSS: you should update to the JavaScript + HTML + CSS linter as required by the project [requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/7_mobile_menu.md#:~:text=you%20should%20add%20the%20JavaScript%20%2B%20HTML%20%2B%20CSS%20linter.). The linter helps you to write clean and consistent code that follows the best practices and standards. You are currently using the HTML + CSS linter only, which does not check for JavaScript errors or style issues. This is the first project where you are asked to use JavaScript and you will therefore need to add JavaScript linters. You can find the complete JavaScript + HTML + CSS linter setup here: https://github.com/microverseinc/linters-config/tree/master/html-css-js

Please note that this suggestion is optional and does not affect your approval status. However, it is highly recommended that you follow it for the next projects to avoid any potential issues or invalidations. Thank you.😊 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
